"""empty message

Revision ID: 1491084b5ee3
Revises: 438075cb3594
Create Date: 2025-04-16 23:29:04.887486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1491084b5ee3'
down_revision = '438075cb3594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('naves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('usuario_nave',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nave_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nave_id'], ['naves.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'nave_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_nave')
    op.drop_table('naves')
    # ### end Alembic commands ###
