"""empty message

Revision ID: bd5deabbf475
Revises: 1491084b5ee3
Create Date: 2025-04-16 23:54:13.977620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5deabbf475'
down_revision = '1491084b5ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('height', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=False))
        batch_op.drop_constraint('personajes_name_key', type_='unique')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('gravity', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('planetas_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.create_unique_constraint('planetas_name_key', ['name'])
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('gravity')
        batch_op.drop_column('diameter')
        batch_op.drop_column('climate')

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_unique_constraint('personajes_name_key', ['name'])
        batch_op.drop_column('image_url')
        batch_op.drop_column('height')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
